sudo: required
language: java
install: true
script: "./gradlew shadowJar"
deploy:
  provider: releases
  api_key:
    secure: Y30oqb2wAccWCRd5MMZt/4ZpzAZzhnCDq8BIE7t9D1JT2AxCY5QSFkyVODPpfoDf1rDWCRk7A73tgzowDIKhNi2pbYSKOlc6mmxa6B+x354F0ujMWN/VROpEWrDKWCGriHYFZYHVZ0nLIq6edS2LMetXlxphiHCYYQV/Z9rdfKHwDxfqWJqqAanXZtztCwFip4Xa+haFAo28RxAUXkrVhtqZW0M548LhRrJc16QApoFuwCcaUj54yKy9QjbIXBgO1rHIPVMV+4zy1WD3edZ5DdykOiNmixL1iOD6TBf+VhYfgzKvidAHJzOyf4zo6c+RyW89zlN5GuDccVYZ2XoO7cl+vMLWSauISYRYvBsje7ef9J2NWrWj6ucubEtiUqSzlovfef0RkmTOdBS3ngmhdMwkqpPLQICoKAJ2cgGkwbG9qV4LA9VaLsxeJ4Fpas5TMb6UyxFLZ8t/ukH2bHJGY+lrYmpFa3lZS9q8+CsCt+6410mkpgpPq4q4vrj25z7jlw2XmIN7+AxZuVdZO3JStmt1EEv/N6qKYfaTk/ikHHoYbfOokpfg5uKIWzi8Rgn2wW6BauPw7//ExBF/n6wVmFKWx/IVNMDIr/RYD+cS4ZBON5kf9iJQyp2+rKYH9QxKZ+t6axfQrAXSlrmsPqPXUDaXV0fV1aVXFw6a6weDOME=
  file: build\libs\xlr-rqmjazz-plugin-1.0.0-all.jar
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xlr-rqmjazz-plugin
